name: fork 元の更新をこのリポジトリに同期

on:
  schedule:
    #　毎月 1日の 10:00am (Japan time) に実行
    - cron:  '0 1 1 * *'
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        # 環境変数
        env:
          NAME: merge-bot
          EMAIL: ysekiy+mergebot@amazon.com
          REPO_FORK: https://github.com/Utree/original.git
        # 追従処理
        run: |
          git config --global user.name ${NAME}
          git config --global user.email ${EMAIL}
          git config --global pull.rebase false

          : # 自身のリポジトリのmainブランチにチェックアウト
          : # pull
          git pull --unshallow origin main

          : # フォーク元のリポジトリをリモート先として "upstream" と命名
          git remote add upstream ${REPO_FORK}
          : # upstream のブランチをローカルに取得
          git fetch upstream main
          git checkout -b main origin/main
          : # マージ
          git merge -m "auto-sync" --no-ff upstream/main
          : # プッシュ
          git push origin main
